[package]
description = "Transport agnostic rust implementation of JSON-RPC 2.0 Specification."
homepage = "https://github.com/ethcore/jsonrpc-core"
repository = "https://github.com/ethcore/jsonrpc-core"
license = "MIT"
name = "jsonrpc-core"
version = "2.0.6"
authors = ["debris <marek.kotewicz@gmail.com>"]
keywords = ["jsonrpc", "json-rpc", "json", "rpc", "serde"]
build = "build.rs"
documentation = "https://ethcore.github.io/jsonrpc-core/jsonrpc_core/index.html"

[dependencies]
# always carefully check serde versions before an update
serde = "0.7.0"
serde_json = "0.7.0"
serde_macros = { "version" = "0.7.0", "optional" = true }

[build-dependencies]
serde_codegen = { "version" = "0.7.0", "optional" = true }
syntex = "0.35.0"

[features]
default = ["serde_codegen"]
nightly = ["serde_macros"]
