[package]
description = "Rust http server using JSONRPC 2.0."
homepage = "https://github.com/debris/jsonrpc-http-server"
license = "MIT"
name = "jsonrpc-http-server"
version = "3.0.0"
authors = ["debris <marek.kotewicz@gmail.com>"]
keywords = ["jsonrpc", "json-rpc", "json", "rpc", "server"]

[dependencies]
jsonrpc-core = "2.0"
hyper = { version = "0.7", default-features = false }
unicase = "1.3"
