[package]
description = "Rust http server using JSONRPC 2.0."
homepage = "https://github.com/debris/jsonrpc-http-server"
license = "MIT"
name = "jsonrpc-http-server"
version = "5.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]
keywords = ["jsonrpc", "json-rpc", "json", "rpc", "server"]

[dependencies]
jsonrpc-core = { git = "https://github.com/ethcore/jsonrpc-core" }
hyper = { default-features = false, git = "https://github.com/ethcore/hyper" }
unicase = "1.3"
