[package]
description = "Transport agnostic rust implementation of JSON-RPC 2.0 Specification."
homepage = "https://github.com/debris/jsonrpc-core"
license = "MIT"
name = "jsonrpc-core"
version = "1.1.2"
authors = ["debris <marek.kotewicz@gmail.com>"]
keywords = ["jsonrpc", "json-rpc", "json", "rpc", "serde"]
build = "build.rs"

[dependencies]
# always carefully check serde versions before an update
serde = "0.6.7"
serde_json = "0.6.0"
serde_macros = { "version" = "0.6.13", "optional" = true }

[build-dependencies]
serde_codegen = { "version" = "0.6.13", "optional" = true }
syntex = "0.28.0"

[features]
default = ["serde_codegen"]
nightly = ["serde_macros"]
