[package]
name = "json-ipc-server"
version = "0.2.0"
authors = ["Nikolay Volf <nikvolf@gmail.com>"]

[dependencies]
jsonrpc-core = "2.0"
mio = "0.5"
slab   = "0.1.0"
bytes  = "0.3.0"
miow = "0.1"

[dev-dependencies]
rand = "0.3"