[package]
name = "jsonrpc-server-utils"
version = "6.0.0"
authors = ["tomusdrw <tomasz@parity.io>"]

[dependencies]
jsonrpc-core = { version = "6.0", path = "../core" }
tokio-core = { version = "0.1" }
