[package]
name = "jsonrpc-server-utils"
version = "7.0.0"
authors = ["tomusdrw <tomasz@parity.io>"]
license = "MIT"

[dependencies]
globset = "0.1"
log = "0.3"
jsonrpc-core = { version = "7.0", path = "../core" }
tokio-core = { version = "0.1" }
tokio-io = { version = "0.1" }
