[package]
name = "jsonrpc-ws-server"
description = "WebSockets server for JSON-RPC"
version = "8.0.0"
authors = ["tomusdrw <tomasz@parity.io>"]
license = "MIT"
homepage = "https://github.com/paritytech/jsonrpc"
repository = "https://github.com/paritytech/jsonrpc"
documentation = "https://paritytech.github.io/jsonrpc/json_ws_server/index.html"

[dependencies]
log = "0.3"
jsonrpc-core = { version = "8.0", path = "../core" }
jsonrpc-server-utils = { version = "8.0", path = "../server-utils" }
ws = { git = "https://github.com/tomusdrw/ws-rs" }
parking_lot = "0.4"
slab = "0.3"

[badges]
travis-ci = { repository = "paritytech/jsonrpc", branch = "master"}
