[package]
name = "jsonrpc-ws-server"
description = "WebSockets server for JSON-RPC"
version = "6.0.0"
authors = ["tomusdrw <tomasz@parity.io>"]
license = "MIT"
homepage = "https://github.com/ethcore/jsonrpc"
repository = "https://github.com/ethcore/jsonrpc"
documentation = "https://ethcore.github.io/jsonrpc/json_ws_server/index.html"

[dependencies]
log = "0.3"
jsonrpc-core = { version = "6.0", path = "../core" }
ws = { git = "https://github.com/tomusdrw/ws-rs" }
