[package]
name = "jsonrpc-tcp-server"
description = "TCP/IP server for JSON-RPC"
version = "7.0.0"
authors = ["NikVolf <nikvolf@gmail.com>"]
license = "MIT"
homepage = "https://github.com/ethcore/jsonrpc"
repository = "https://github.com/ethcore/jsonrpc"
documentation = "https://ethcore.github.io/jsonrpc/json_tcp_server/index.html"

[dependencies]
log = "0.3"
parking_lot = "0.3"
serde_json = "0.9"
tokio-service = "0.1"

jsonrpc-core = { version = "7.0", path = "../core" }
jsonrpc-server-utils = { version = "7.0", path = "../server-utils" }

[dev-dependencies]
lazy_static = "0.2"
env_logger = "0.4"
