[package]
name = "jsonrpc-tcp-server"
description = "TCP/IP server for JSON-RPC"
version = "7.1.1"
authors = ["NikVolf <nikvolf@gmail.com>"]
license = "MIT"
homepage = "https://github.com/paritytech/jsonrpc"
repository = "https://github.com/paritytech/jsonrpc"
documentation = "https://paritytech.github.io/jsonrpc/json_tcp_server/index.html"

[dependencies]
log = "0.3"
parking_lot = "0.4"
tokio-service = "0.1"
jsonrpc-core = { version = "7.1", path = "../core" }
jsonrpc-server-utils = { version = "7.1", path = "../server-utils" }

[dev-dependencies]
lazy_static = "0.2"
env_logger = "0.4"

[badges]
travis-ci = { repository = "paritytech/jsonrpc", branch = "master"}
