[package]
description = "Helper macros for jsonrpc-core"
homepage = "https://github.com/ethcore/jsonrpc"
repository = "https://github.com/ethcore/jsonrpc"
license = "MIT"
name = "jsonrpc-macros"
version = "0.1.0"
authors = ["rphmeier <robert@ethcore.io>"]
keywords = ["jsonrpc", "json-rpc", "json", "rpc", "macros"]
documentation = "https://ethcore.github.io/jsonrpc/jsonrpc_macros/index.html"

[dependencies]
serde = "0.8"
futures = "0.1.6"
jsonrpc-core = { version = "5.0", path = "../core" }
