[package]
description = "Helper macros for jsonrpc-core"
homepage = "https://github.com/ethcore/jsonrpc"
repository = "https://github.com/ethcore/jsonrpc"
license = "MIT"
name = "jsonrpc-macros"
version = "6.0.0"
authors = ["rphmeier <robert@ethcore.io>"]
keywords = ["jsonrpc", "json-rpc", "json", "rpc", "macros"]
documentation = "https://ethcore.github.io/jsonrpc/jsonrpc_macros/index.html"

[dependencies]
serde = "0.9"
jsonrpc-core = { version = "6.0", path = "../core" }
jsonrpc-pubsub = { version = "6.0", path = "../pubsub" }

[dev-dependencies]
jsonrpc-tcp-server = { version = "6.0", path = "../tcp" }
