[package]
description = "Publish-Subscribe extension for jsonrpc."
homepage = "https://github.com/paritytech/jsonrpc"
repository = "https://github.com/paritytech/jsonrpc"
license = "MIT"
name = "jsonrpc-pubsub"
version = "7.0.0"
authors = ["tomusdrw <tomasz@parity.io>"]
keywords = ["jsonrpc", "json-rpc", "json", "rpc", "macros"]
documentation = "https://paritytech.github.io/jsonrpc/jsonrpc_pubsub/index.html"

[dependencies]
log = "0.3"
parking_lot = "0.4"
jsonrpc-core = { version = "7.0", path = "../core" }

[dev-dependencies]
jsonrpc-tcp-server = { version = "7.0", path = "../tcp" }
jsonrpc-ws-server = { version = "7.0", path = "../ws" }
