[package]
description = "Publish-Subscribe extension for jsonrpc."
homepage = "https://github.com/ethcore/jsonrpc"
repository = "https://github.com/ethcore/jsonrpc"
license = "MIT"
name = "jsonrpc-pubsub"
version = "6.0.0"
authors = ["tomusdrw <tomasz@parity.io>"]
keywords = ["jsonrpc", "json-rpc", "json", "rpc", "macros"]
documentation = "https://ethcore.github.io/jsonrpc/jsonrpc_pubsub/index.html"

[dependencies]
parking_lot = "0.3"
jsonrpc-core = { version = "6.0", path = "../core" }

[dev-dependencies]
jsonrpc-tcp-server = { version = "6.0", path = "../tcp" }
